#version: "3"

networks:
  bigSystemNetwork:
    driver: bridge

services:
  mainDatabase:
    image: mysql:8.0.38
    container_name: mainDatabase
    hostname: mainDatabase
    networks:
      - bigSystemNetwork
    ports:
      - "3306:3306"
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/init.sql
