networks:
  elastic-network:
    driver: bridge

services:
  # 로그 저장을 하기 위한 elasticsearch
  logElasticSearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    container_name: logElasticSearchServer
    hostname: elasticsearch
    volumes:
      - "./elasticsearch/data:/usr/share/elasticsearch/data"
    networks:
      - elastic-network
    ports:
      - "9200:9200"
    environment:
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - discovery.type=single-node
    logging:
      options:
        max-size: "10MB"
        max-file: "3"
  collectorLogStash:
    image: docker.elastic.co/logstash/logstash:8.10.0
    container_name: logStashServer
    depends_on:
      - logElasticSearch
    volumes:
      - "./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro"
    networks:
      - elastic-network
    ports:
      - "5044:5044"
      - "9600:0600"
    logging:
      options:
        max-size: "10MB"
        max-file: "3"
  logKibana:
    container_name: logKibana
    hostname: kibana
    image: kibana:8.10.1
    depends_on:
      - logElasticSearch
    ports:
      - "5601:5601"
    networks:
      - elastic-network
    environment:
      - ELASTICSEARCH_HOSTS=http://logElasticSearchServer:9200
    #      - ELASTICSEARCH_USERNAME=
    #      - ELASTICSEARCH_PASSWORD=
    logging:
      options:
        max-size: "10MB"
        max-file: "3"