server:
  port: 9002
  shutdown: graceful

spring:
  application:
    name: board-article-like-service
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${ARTICLE_LIKE_DB_URL}
    username: ${ARTICLE_DB_USER}
    password: ${ARTICLE_DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    database: mysql
    mapping-resources:
      - META-INF/orm.xml

logging:
  level:
    root: info