server:
  port: 9000
  shutdown: graceful

spring:
  config:
    import: optional:file:.env[.properties] # env file
  #    import: optional:application-db.yml # h2 database
  application:
    name: board-article-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${ARTICLE_DB_URL}
    username: ${ARTICLE_DB_USER}
    password: ${ARTICLE_DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none