server:
  port: 9000
  shutdown: graceful

spring:
  #  config:
  #    import: optional:application-db.yml # h2 database
  application:
    name: board-article-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none